nodule_insert_template = [
    "A 1.2 cm nodule in the right upper lobe.",
    "There appears to be a 1.5 cm nodule in the left lower lobe with smooth borders.",
    "A 2.3 cm nodule in the right middle lobe.",
    "A 2.7 cm nodule in the left upper lobe with well defined margins.",
    "A 1.8 cm nodule in the right lower lobe.",
    "A 2.0 cm nodule in the left middle lobe.",
    "There is a 1.3 cm nodule, seen in the right upper lobe with smooth contours.",
    "A 2.5 cm nodule in the left lower lobe.",
    "A 2.1 cm nodule in the right middle lobe with irregular borders.",
    "Noted: a 1.9 cm nodule in the left upper lobe.",
    "A 2.8 cm nodule in the right lower lobe with smooth margins.",
    "A 1.7 cm nodule in the left middle lobe.",
    "A 2.2 cm nodule in the right upper lobe with well defined borders.",
    "A 1.4 cm nodule in the left lower lobe.",
    "A 2.6 cm nodule in the right middle lobe with smooth margins.",
    "A 1.8 cm nodule is evident in the left upper lobe.",
    "A 2.0 cm nodule in the right lower lobe with subtle irregularity.",
    "A 1.5 cm nodule in the left middle lobe.",
    "Findings include a 2.4 cm nodule in the right upper lobe with smooth contours.",
    "A 2.9 cm nodule in the left lower lobe.",
    "A 1.6 cm nodule in the right middle lobe.",
    "A 2.1 cm nodule in the left upper lobe with well defined margins.",
    "A 1.7 cm nodule in the right lower lobe.",
    "A 2.3 cm nodule in the left middle lobe with smooth borders.",
    "A 2.5 cm nodule in the right upper lobe.",
    "A 3.2 cm mass in the right upper lobe.",
    "A 3.5 cm mass in the left lower lobe with irregular margins.",
    "A 4 cm mass in the right middle lobe.",
    "Noted is a 3.8 cm mass in the left upper lobe with smooth contours.",
    "A 4.2 cm mass in the right lower lobe.",
    "A 3.7 cm mass in the left middle lobe.",
    "A 3.9 cm mass in the right upper lobe with spiculated edges.",
    "A 4.5 cm mass in the left lower lobe.",
    "A 3.3 cm mass in the right middle lobe.",
    "A 4.1 cm mass in the left upper lobe with irregular borders.",
    "A 3.6 cm mass in the right lower lobe.",
    "A 4.3 cm mass in the left middle lobe with well defined margins.",
    "A 3.2 cm mass in the right upper lobe.",
    "A 3.8 cm mass in the left lower lobe.",
    "A 4 cm mass in the right middle lobe with smooth borders.",
    "A 3.5 cm mass in the left upper lobe.",
    "A 4.2 cm mass in the right lower lobe with subtle irregularity.",
    "A 3.7 cm mass in the left middle lobe.",
    "There appears to be a 4.5 cm mass in the right upper lobe with well defined contours.",
    "A 3.3 cm mass in the left lower lobe.",
    "A 4.1 cm mass in the right middle lobe.",
    "A 3.6 cm mass in the left upper lobe with irregular margins.",
    "A 4.3 cm mass in the right lower lobe.",
    "A 3.9 cm mass in the left middle lobe with smooth contours.",
    "A 4 cm mass in the right upper lobe.",
    "Two lung nodules in the right upper lobe, the largest measuring 2.0 cm.",
    "Two lung nodules in the left lower lobe, with the largest at 2.5 cm.",
    "Two lung nodules in the right middle lobe, the largest measuring 2.2 cm with smooth margins.",
    "Two lung nodules in the left upper lobe, the largest being 2.8 cm.",
    "Two lung nodules in the right lower lobe, largest measuring 1.9 cm.",
    "Two lung nodules in the left middle lobe, with the largest at 2.3 cm.",
    "Two lung nodules in the right upper lobe, the largest measuring 2.4 cm with well defined borders.",
    "Two lung nodules in the left lower lobe, the largest measuring 2.1 cm.",
    "Two lung nodules in the right middle lobe, largest measuring 2.7 cm.",
    "Two lung nodules in the left upper lobe, with the largest being 2.0 cm.",
    "Two lung nodules in the right lower lobe, the largest measuring 2.6 cm.",
    "Two lung nodules in the left middle lobe, with the largest at 2.3 cm.",
    "Three lung nodules in the right upper lobe, the largest measuring 2.8 cm.",
    "Three lung nodules in the left lower lobe, with the largest at 2.0 cm.",
    "Three lung nodules in the right middle lobe, the largest measuring 2.4 cm with smooth margins.",
    "Three lung nodules in the left upper lobe, the largest being 2.6 cm.",
    "Three lung nodules in the right lower lobe, largest measuring 2.3 cm.",
    "Three lung nodules in the left middle lobe, with the largest at 2.7 cm.",
    "Three lung nodules in the right upper lobe, the largest measuring 2.5 cm.",
    "Three lung nodules in the left lower lobe, the largest measuring 2.2 cm.",
    "Three lung nodules in the right middle lobe, largest measuring 2.9 cm.",
    "Three lung nodules in the left upper lobe, with the largest at 2.4 cm.",
    "Three lung nodules in the right lower lobe, the largest measuring 2.8 cm.",
    "Three lung nodules in the left middle lobe, largest measuring 2.6 cm.",
    "Two lung nodules in the right upper lobe.",
    "Two lung nodules are observed in the left lower lobe.",
    "Two lung nodules appear in the right middle lobe.",
    "Two lung nodules can be seen in the left upper lobe.",
    "There are two lung nodules in the right lower lobe.",
    "Two nodules are identified in the left middle lobe.",
    "Two lung nodules are present in the right upper lobe.",
    "Two nodules are noted in the left lower lobe.",
    "Two lung nodules are detected in the right middle lobe.",
    "Two nodules are seen in the left upper lobe.",
    "Three lung nodules are noted in the right upper lobe.",
    "Three lung nodules are observed in the left lower lobe.",
    "Three lung nodules appear in the right middle lobe.",
    "Three lung nodules can be seen in the left upper lobe.",
    "There are three lung nodules in the right lower lobe.",
    "Three nodules are identified in the left middle lobe.",
    "Three lung nodules are present in the right upper lobe.",
    "Three nodules are noted in the left lower lobe.",
    "Three lung nodules are detected in the right middle lobe.",
    "Three nodules are seen in the left upper lobe.",
    "A 0.8 cm nodule in the right upper lobe.",
    "A 1.2 cm nodule in the left lower lobe.",
    "A 1.5 cm nodule in the right middle lobe.",
    "A 2.0 cm nodule in the left upper lobe.",
    "A 0.7 cm nodule in the right lower lobe.",
    "A 1.8 cm nodule in the right upper lobe.",
    "A 2.2 cm nodule in the left lower lobe.",
    "A 0.9 cm nodule in the right middle lobe.",
    "A 1.6 cm nodule in the left upper lobe.",
    "Small nodule in the right lower lobe.",
    "Nodule noted in the left upper lobe.",
    "Nodule seen in the right upper lobe.",
    "Nodule identified in the left lower lobe.",
    "Nodule present in the right middle lobe.",
    "Small nodule observed in the left upper lobe.",
    "Tiny nodule in the right lower lobe.",
    "Nodule visualized in the left lower lobe.",
    "Nodule found in the right upper lobe.",
    "Small nodule detected in the left lower lobe.",
    "Nodule in the right middle lobe.",
    "Nodule in the left upper lobe.",
    "Nodule in the right lower lobe.",
    "A 2.1 cm partially solid nodule identified in the right middle lobe.",
    "Multiple nodules observed in the left upper lobe, the largest measuring 1.4 cm.",
    "A 3.2 cm mass in the right lower lobe with irregular borders.",
    "A 2.5 cm nodule in the right upper lobe showing calcification.",
    "An irregular 1.7 cm nodule noted in the left lower lobe with peripheral ground-glass halo.",
    "A 2.8 cm mass-like lesion in the left upper lobe with associated pleural retraction.",
    "A 1.3 cm part-solid nodule identified in the right lower lobe.",
    "Multiple small nodules scattered throughout both lungs, ranging from 0.4 to 0.7 cm.",
    "A 2.2 cm spiculated mass in the left lower lobe suspicious for primary lung malignancy.",
    "A 1.5 cm cavitary nodule in the right upper lobe.",
    "A 3.5 cm heterogeneous mass noted in the left upper lobe with central necrosis.",
    "A 1.2 cm perifissural nodule observed in the right middle lobe.",
    "A 2.4 cm nodule in the left lower lobe with surrounding ground-glass opacity.",
    "A 1.8 cm juxtapleural nodule noted in the right upper lobe.",
    "Multiple bilateral pulmonary nodules, the dominant nodule measuring 2.6 cm in the left upper lobe.",
    "A 3.0 cm mass with lobulated margins in the left upper lobe.",
    "A 1.4 cm nodule with internal air bronchogram in the right middle lobe.",
    "A cluster of nodules in the left lower lobe, the largest measuring 1.9 cm.",
    "A 2.7 cm mass-like opacity noted in the right upper lobe with spiculated margins.",
    "A 1.0 cm ground-glass nodule in the left upper lobe.",
    "Multiple bilateral pulmonary nodules measuring up to 1.6 cm, suggestive of metastatic disease.",
    "A 2.9 cm irregular mass identified in the right lower lobe with associated pleural thickening.",
    "A 1.3 cm solid nodule noted in the left upper lobe with smooth borders.",
    "A 2.3 cm part-solid nodule in the right upper lobe with air bronchograms.",
    "A 0.7 cm calcified nodule observed in the left lower lobe.",
    "A 3.3 cm spiculated mass in the right middle lobe concerning for primary lung cancer.",
    "Multiple nodules noted bilaterally, ranging from 0.5 to 2.0 cm in size.",
    "A 1.7 cm subsolid nodule identified in the left upper lobe.",
    "A 2.6 cm mass with central cavitation in the right lower lobe.",
    "A 1.2 cm well-defined nodule noted in the right upper lobe.",
    "A 1.9 cm smoothly marginated nodule in the right upper lobe.",
    "A 2.1 cm nodule in the left lower lobe with subtle surrounding ground-glass opacity.",
    "Multiple small pulmonary nodules scattered in the left lung.",
    "A 2.7 cm nodule in the right lower lobe, likely granulomatous in etiology.",
    "A 1.6 cm nodule detected in the left upper lobe with irregular borders.",
    "A 2.3 cm spiculated nodule in the right middle lobe with pleural contact.",
    "A 1.1 cm nodule with a smooth border in the left lower lobe.",
    "Multiple pulmonary nodules present bilaterally, the largest measuring 1.5 cm in the right upper lobe.",
    "A 3.0 cm well-defined mass in the left upper lobe.",
    "A 2.5 cm irregular nodule in the right lower lobe.",
    "A 1.7 cm nodule with a lobulated border in the left lower lobe.",
    "A 2.8 cm spiculated nodule in the right upper lobe, suspicious for malignancy.",
    "Multiple nodules scattered throughout the right lung.",
    "A 3.4 cm mass in the left lower lobe with associated collapse-consolidation.",
    "A 2.0 cm ground-glass nodule in the right middle lobe.",
    "A 1.5 cm well-circumscribed nodule in the right lower lobe."
    ]

effusion_insert_template = [
    "A small pleural effusion is observed in the right pleural space.",
    "A small pleural effusion is noted in the left hemithorax.",
    "A small pleural effusion is seen at the lung base.",
    "There is a small pleural effusion in the right lung base.",
    "Imaging reveals a small pleural effusion in the left pleural space.",
    "A small pleural effusion is evident in the right hemithorax.",
    "A small effusion is identified in the left lung base.",
    "A small pleural effusion is demonstrated in the right pleural space.",
    "Findings show a small pleural effusion in the left hemithorax.",
    "A small pleural effusion is apparent at the lung base.",
    "CT scan reveals a small pleural effusion in the right pleural space.",
    "Chest CT shows a small pleural effusion in the left hemithorax.",
    "A small pleural effusion is detected at the right lung base.",
    "A small pleural effusion is documented in the left pleural space.",
    "A small pleural effusion is seen in the right hemithorax.",
    "A small effusion is evident at the lung base.",
    "Imaging studies demonstrate a small pleural effusion in the left lung base.",
    "A small pleural effusion is apparent in the right pleural space.",
    "A small pleural effusion is identified in the left hemithorax.",
    "CT imaging reveals a small pleural effusion at the lung base.",
    "A small pleural effusion is observed in the right lung base.",
    "A small pleural effusion is noted in the left pleural space.",
    "A small pleural effusion is seen in the right hemithorax.",
    "CT imaging shows a small pleural effusion at the lung base.",
    "A small pleural effusion is evident in the left pleural space.",
    "Imaging indicates a small pleural effusion in the right hemithorax.",
    "A small pleural effusion is detected at the left lung base.",
    "A small pleural effusion is documented in the right pleural space.",
    "A small pleural effusion is apparent in the left hemithorax.",
    "Imaging demonstrates a small pleural effusion at the lung base.",
    "A small pleural effusion is observed in the right lung base.",
    "A small pleural effusion is noted in the left pleural space.",
    "A small pleural effusion is evident in the right hemithorax.",
    "Chest CT reveals a small pleural effusion at the lung base.",
    "A small pleural effusion is identified in the left pleural space.",
    "CT scan demonstrates a small pleural effusion in the right hemithorax.",
    "A small pleural effusion is observed at the left lung base.",
    "Imaging indicates a small pleural effusion in the right pleural space.",
    "A small pleural effusion is noted in the left hemithorax.",
    "Findings reveal a small pleural effusion at the lung base.",
    "A small pleural effusion is observed in the right lung base.",
    "A small pleural effusion is documented in the left pleural space.",
    "CT imaging reveals a small pleural effusion in the right hemithorax.",
    "A small pleural effusion is evident at the lung base.",
    "Imaging studies reveal a small pleural effusion in the left pleural space.",
    "A small pleural effusion is identified in the right hemithorax.",
    "A small pleural effusion is observed at the lung base.",
    "A small pleural effusion is noted in the left pleural space.",
    "Findings demonstrate a small pleural effusion in the right hemithorax.",
    "A small pleural effusion is apparent at the lung base.",
    "CT scan reveals a small pleural effusion in the left pleural space.",
    "A small pleural effusion is detected in the right hemithorax.",
    "Imaging indicates a small pleural effusion at the lung base.",
    "A small pleural effusion is observed in the left pleural space.",
    "A small pleural effusion is noted in the right hemithorax.",
    "A small pleural effusion is evident at the lung base.",
    "A small pleural effusion is identified in the left pleural space.",
    "A moderate pleural effusion is observed in the right pleural space.",
    "A moderate pleural effusion is noted in the left hemithorax.",
    "A moderate pleural effusion is seen at the lung base.",
    "There is a moderate pleural effusion in the right lung base.",
    "Imaging reveals a moderate pleural effusion in the left pleural space.",
    "A moderate pleural effusion is evident in the right hemithorax.",
    "A moderate effusion is identified in the left lung base.",
    "A moderate pleural effusion is demonstrated in the right pleural space.",
    "Findings show a moderate pleural effusion in the left hemithorax.",
    "A moderate pleural effusion is apparent at the lung base.",
    "CT scan reveals a moderate pleural effusion in the right pleural space.",
    "Chest CT shows a moderate pleural effusion in the left hemithorax.",
    "A moderate pleural effusion is detected at the right lung base.",
    "A moderate pleural effusion is documented in the left pleural space.",
    "A moderate pleural effusion is seen in the right hemithorax.",
    "Imaging indicates a moderate pleural effusion at the lung base.",
    "A moderate pleural effusion is observed in the left pleural space.",
    "A moderate pleural effusion is noted in the right hemithorax.",
    "Findings reveal a moderate pleural effusion at the lung base.",
    "A moderate pleural effusion is identified in the left pleural space.",
    "CT imaging demonstrates a moderate pleural effusion in the right hemithorax.",
    "A moderate pleural effusion is observed at the lung base.",
    "Imaging indicates a moderate pleural effusion in the left pleural space.",
    "A large pleural effusion is observed in the right pleural space.",
    "A large pleural effusion is noted in the left hemithorax.",
    "A large pleural effusion is seen at the lung base.",
    "There is a large pleural effusion in the right lung base.",
    "Imaging reveals a large pleural effusion in the left pleural space.",
    "A large pleural effusion is evident in the right hemithorax.",
    "A large effusion is identified in the left lung base.",
    "A large pleural effusion is demonstrated in the right pleural space.",
    "Findings show a large pleural effusion in the left hemithorax.",
    "A large pleural effusion is apparent at the lung base."
    ]